"""update table vehiculo

Revision ID: 26ee8863839a
Revises: 12b487b8c1a4
Create Date: 2024-10-27 17:54:14.255620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '26ee8863839a'
down_revision: Union[str, None] = '12b487b8c1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculo', sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('vehiculo', sa.Column('kilometraje', sa.Integer(), nullable=False))
    op.add_column('vehiculo', sa.Column('capacidad', sa.Float(), nullable=False))
    op.add_column('recoleccion', sa.Column('vehiculo_placa', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('recoleccion_vehiculo_id_fkey', 'recoleccion', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculo', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vehiculo', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('vehiculo', 'capacidad')
    op.drop_column('vehiculo', 'kilometraje')
    op.drop_column('vehiculo', 'placa')
    op.create_index('fki_usuario_users_id_fkey', 'usuario', ['id'], unique=False)
    op.create_index('fki_recoleccionparticular_recoleccion_id_fkey', 'recoleccionparticular', ['recoleccion_id'], unique=False)
    op.alter_column('recoleccionparticular', 'recoleccion_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('recoleccion', sa.Column('vehiculo_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recoleccion', type_='foreignkey')
    op.create_foreign_key('recoleccion_vehiculo_id_fkey', 'recoleccion', 'vehiculo', ['vehiculo_id'], ['id'])
    op.drop_column('recoleccion', 'vehiculo_placa')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    # ### end Alembic commands ###
