"""add promedios and general Residuos tables

Revision ID: 331891168ad0
Revises: 4ab44188abce
Create Date: 2024-10-28 14:48:50.689830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '331891168ad0'
down_revision: Union[str, None] = '4ab44188abce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promedioresiduos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('punto_recoleccion_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_residuo_id', sa.Uuid(), nullable=False),
    sa.Column('promedio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['punto_recoleccion_id'], ['puntorecoleccion.id'], ),
    sa.ForeignKeyConstraint(['tipo_residuo_id'], ['tiporesiduo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residuo',
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_residuo_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_residuo_id'], ['tiporesiduo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('recoleccion', 'vehiculo_placa',
    #            existing_type=sa.UUID(),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=False)
    # op.create_foreign_key(None, 'recoleccion', 'vehiculo', ['vehiculo_placa'], ['placa'])
    # op.drop_index('fki_usuario_users_id_fkey', table_name='usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fki_usuario_users_id_fkey', 'usuario', ['id'], unique=False)
    op.drop_constraint(None, 'recoleccion', type_='foreignkey')
    op.alter_column('recoleccion', 'vehiculo_placa',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_table('residuo')
    op.drop_table('promedioresiduos')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
