"""add promedios and general Residuos tables

Revision ID: 4ab44188abce
Revises: 8b994dbb1fe4
Create Date: 2024-10-28 14:37:47.160446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ab44188abce'
down_revision: Union[str, None] = '8b994dbb1fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barrido', sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('barrido', 'observaciones')
    op.add_column('puntorecoleccion', sa.Column('promedio_residuos', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'recoleccion', 'tiporesiduo', ['tipo_residuo_id'], ['id'])
    op.create_foreign_key(None, 'recoleccion', 'ruta', ['ruta_id'], ['id'])
    # op.drop_column('recoleccion', 'vehiculo_id')
    op.drop_index('fki_recoleccionparticular_recoleccion_id_fkey', table_name='recoleccionparticular')
    op.add_column('tiporesiduo', sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tiporesiduo', sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tiporesiduo', sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('tiporesiduo', 'nombre')
    op.add_column('usuario', sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('usuario', sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('usuario', sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    #op.drop_index('fki_usuario_users_id_fkey', table_name='usuario')
    # op.add_column('usuariorecoleccion', sa.Column('usuario_id', sa.Uuid(), nullable=False))
    # op.add_column('usuariorecoleccion', sa.Column('recoleccion_id', sa.Uuid(), nullable=False))
    # op.drop_constraint('usuariorecoleccion_id_recoleccion_fkey', 'usuariorecoleccion', type_='foreignkey')
    # op.drop_constraint('usuariorecoleccion_id_usuario_fkey', 'usuariorecoleccion', type_='foreignkey')
    # op.create_foreign_key(None, 'usuariorecoleccion', 'recoleccion', ['recoleccion_id'], ['id'])
    # op.create_foreign_key(None, 'usuariorecoleccion', 'usuario', ['usuario_id'], ['id'])
    # op.drop_column('usuariorecoleccion', 'id_usuario')
    # op.drop_column('usuariorecoleccion', 'id_recoleccion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuariorecoleccion', sa.Column('id_recoleccion', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('usuariorecoleccion', sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuariorecoleccion', type_='foreignkey')
    op.drop_constraint(None, 'usuariorecoleccion', type_='foreignkey')
    op.create_foreign_key('usuariorecoleccion_id_usuario_fkey', 'usuariorecoleccion', 'usuario', ['id_usuario'], ['id'])
    op.create_foreign_key('usuariorecoleccion_id_recoleccion_fkey', 'usuariorecoleccion', 'recoleccion', ['id_recoleccion'], ['id'])
    op.drop_column('usuariorecoleccion', 'recoleccion_id')
    op.drop_column('usuariorecoleccion', 'usuario_id')
    op.create_index('fki_usuario_users_id_fkey', 'usuario', ['id'], unique=False)
    op.drop_column('usuario', 'documento')
    op.drop_column('usuario', 'tipo_documento')
    op.drop_column('usuario', 'nombre')
    op.add_column('tiporesiduo', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tiporesiduo', 'observacion')
    op.drop_column('tiporesiduo', 'descripcion')
    op.drop_column('tiporesiduo', 'categoria')
    op.create_index('fki_recoleccionparticular_recoleccion_id_fkey', 'recoleccionparticular', ['recoleccion_id'], unique=False)
    op.add_column('recoleccion', sa.Column('vehiculo_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recoleccion', type_='foreignkey')
    op.drop_constraint(None, 'recoleccion', type_='foreignkey')
    op.drop_column('puntorecoleccion', 'promedio_residuos')
    op.add_column('barrido', sa.Column('observaciones', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('barrido', 'observacion')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
