"""update table FK vehiculo

Revision ID: 8b994dbb1fe4
Revises: 26ee8863839a
Create Date: 2024-10-27 18:06:26.583847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b994dbb1fe4'
down_revision: Union[str, None] = '26ee8863839a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vehiculo_pkey', 'vehiculo', type_='primary')
    op.create_primary_key('vehiculo_pkey', 'vehiculo', ['placa'])
    
    op.drop_column('vehiculo', 'id')
    op.create_foreign_key(None, 'recoleccion', 'vehiculo', ['vehiculo_placa'], ['placa'])
    op.drop_column('recoleccion', 'vehiculo_id')
    op.alter_column('recoleccionparticular', 'recoleccion_id',
               existing_type=sa.UUID(),
               nullable=False)
    
    op.drop_column('vehiculo', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculo', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vehiculo', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index('fki_usuario_users_id_fkey', 'usuario', ['id'], unique=False)
    op.create_index('fki_recoleccionparticular_recoleccion_id_fkey', 'recoleccionparticular', ['recoleccion_id'], unique=False)
    op.alter_column('recoleccionparticular', 'recoleccion_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('recoleccion', sa.Column('vehiculo_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recoleccion', type_='foreignkey')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
